name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: integration-test
      run: ./integration-test.sh

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: buckaroobanzay/php
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true
